"""empty message

Revision ID: 4e00d41b207f
Revises: 57a4b2cbec71
Create Date: 2020-10-07 19:13:12.425354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e00d41b207f'
down_revision = '57a4b2cbec71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('startTime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'startTime')
    # ### end Alembic commands ###
